sistemavotocao/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('votacao.urls'), name='votacao'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name="home"),
]

votacao/urls.py
from django.urls import path
from django.contrib import admin

from . import views

app_name = 'votacao'

urlpatterns = [
	
    # User
    path('admin/', admin.site.urls),
    path('newuser/', views.RegisterUser.as_view(), name='newuser'),
    #Proposed_law
    path('propostalista/', views.Proposed_lawListView.as_view(), name='propostalista'),
    path('proposta/<pk>', views.Proposed_lawDetailView.as_view(), name='propostadetalhes'),
    path('propostacreate/', views.Proposed_lawCreateView.as_view(), name='propostacadastro'),
    path('success/', views.Success.as_view(), name = 'success'),
    #Comment
    path('comment/', views.CommentCreateView.as_view(), name='comment'),
    path('comment/update/', views.CommentUpdateView.as_view(), name='updatecomment'),

]

votacao/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from datetime import datetime, timedelta

now = datetime.now()
other_time = now + timedelta(hours=1)

class Proposed_law(models.Model):
	title = models.CharField(max_length=250, verbose_name='titulo')
	description = models.TextField(verbose_name='descrição')
	resultado = models.BooleanField(default = False, verbose_name='resultado')
	final_time = models.TimeField(verbose_name='horario final', default=other_time)
	active = models.BooleanField(default=True, verbose_name='ativado')

	def __str__(self):
		return self.title

	class Meta:
		verbose_name = 'proposta de lei'
		verbose_name_plural = 'propostas de leis'


class Voting(models.Model):
	id_proposed = models.IntegerField(default= 0, verbose_name='id_proposed')
	id_user = models.IntegerField(default= 0, verbose_name='id_user')
	votocontra = models.IntegerField(default = 0, verbose_name='votos contra')
	votoafavor = models.IntegerField(default = 0, verbose_name='votos a favor')

	def __str__(self):
		return 'voto'

	class Meta:
		verbose_name = 'voto'
		verbose_name_plural = 'votos'

class Comment(models.Model):
	id_proposed = models.IntegerField(default= 0, verbose_name='id_proposed')
	id_user = models.IntegerField(default= 0, verbose_name='id_user')	
	comment = models.TextField(verbose_name='Comentario')

	def __str__(self):
		return self.comment

	class Meta:
		verbose_name = 'comentario'
		verbose_name_plural = 'comentarios'



votacao/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView

from django.urls import reverse_lazy

from . import models

class RegisterUser(CreateView):
	form_class = UserCreationForm
	success_url = reverse_lazy('login')
	template_name = 'cadastrousuario.html'

class Proposed_lawCreateView(CreateView):
	model = models.Proposed_law
	template_name = 'cadastroproposta.html'
	fields = ['title', 'description']
	success_url = reverse_lazy('votacao:success')

class Success(TemplateView):
	template_name = 'sucesso.html'

class Proposed_lawListView(ListView):
	model = models.Proposed_law
	template_name = 'listaproposta.html'

class Proposed_lawDetailView(DetailView):
	model = models.Proposed_law
	template_name = 'propostadetail.html'

class CommentCreateView(CreateView):
	model = models.Comment
	template_name = 'comentarios.html'
	success_url = reverse_lazy('votacao:comment')
	fields = ['comment']

class CommentUpdateView(UpdateView):
	model = models.Comment
	template_name = 'comentarioupdate.html'
	success_url = reverse_lazy('votacao:updatecomment')
	fields = ['comment']


		

templates/cadastroproposta.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Cadastro Proposta de Lei</title>
</head>
<body>
	<div style= "width: 300px; text-align: center;">
      <h1>Cadastro de Posposta</h1>
    <form method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit">Cadastre</button>
    </form>
  </div>
</body>
</html>

templates/cadastrousuario.html
<!DOCTYPE>
<html>
<head>
  <meta charset="utf-8">
  <title>Cadastro de Usuario</title>
</head>
<body>
  <div style= "width: 300px; text-align: center;">
      <h1>Cadastro de Usuario</h1>
      <form method="POST">
       {% csrf_token %}
       {{form.as_p}}
      <button type="submit">Cadastre-se</button>
    </form>
  </div>
</body>
</html>

templates/comentarios.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Adicionar Comentarios</title>
</head>
<body>	
	<form method="POST">
		{% for comment in object.comment.all %}
		{% endfor %}
    </form>
</body>
</html>

templates/comentarioupdate.html
<!DOCTYPE html>
<html>
<head>
	<title>Atualização do Comentario</title>
</head>
<body>
	<form method="POST">
		{% csrf_token %}
		{{form.as_p}}
    </form>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Home</title>
</head>
<body>
	<h3>Bem Vindo!</h3>
	<button onclick="location.href='propostacreate/';">Cadastre sua Proposta</button>
	<button onclick="location.href='propostalista/';">Buscar Proposta</button>
</body>
</html>

templates/listaproposta.html
<html>
  <head>
    <title>Listagem das Propostas</title>
  </head>
  <body>
    <ul>
    <h1>Lista de Propostas</h1>
    	<ul>
		    {% for object in object_list %}
		    <li><a href="{% url 'votacao:propostadetalhes' object.pk %}">{{ object }}</a></li>    
		    {% endfor %}
		</ul>
    <a href="{% url 'home' %}">Voltar</a>
    </ul>    
  </body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Login</title>
</head>
<body>
	<div style= "width: 300px; text-align: center;">
      <h1>Login</h1>
      <form method="POST">
       {% csrf_token %}
       {{form.as_p}}
      <button type="submit">Login</button>
    </form>
</body>
</html>

templates/propostadetail.html
<!DOCTYPE html>
<html>
<head>
	<title>Detalhes da Proposta</title>
</head>
<body>
	<h2>{{ object.title }}</h2>
	<p>{{ object.description }}</p>
	<ul>
		<a href="{% url 'votacao:propostalista' %}">Voltar</a>
		<button type="submit">Votar Contra</button>
		<button type="submit">Votar a Favor</button>
		<a href='comment/'><button type="submit">Comentar</button></a>
	</ul>
</body>
</html>

templates/sucesso.html
<!DOCTYPE html>
<html>
<head>
	<title>Sucesso!!</title>
</head>
<body>
	<h2>Deu Certo :)</h2>
	<a href="{% url 'votacao:propostalista' %}">Votar</a>
</body>
</html>